How to disable, enable, and connect with Remote Desktop Protocol (RDP) on Windows 10:

Telegram POST https://t.me/efxtv2/3841

---

Disabling RDP on Windows 10 via PowerShell:

1. Open PowerShell as Administrator.
2. Run this command:
   ```
   Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 1
   ```
3. Verify RDP is disabled in "Remote Settings".
4. Restart if needed.

---

Enabling RDP on Windows 10 via PowerShell:

1. Open PowerShell as Administrator.
2. Run this command:
   ```
   Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
   ```
3. Verify RDP is enabled in "Remote Settings".
4. Restart if needed.

---

Connecting to Windows 10 via RDP from another device:

1. Ensure both devices are on the same network.
2. On the Windows 10 PC:
   - Open "Control Panel" -> "System and Security" -> "System".
   - Click on "Remote settings".
   - Select "Allow remote connections to this computer".
   - Note down the PC name under "Computer name".
3. On the Remote Device (e.g., Another PC):
   - Open Remote Desktop Connection.IP:3389
   - Enter the PC name from Step 2.
   - Enter credentials if prompted.
   - Click "Connect" to establish the RDP session.

---

Enjoy remote access to your Windows 10 PC! #Windows10 #RemoteDesktop

You can now copy and paste this into your Notepad or any text editor for easy reference.
